# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MFB_IOS_PROJECT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MFB_IOS_PROJECT
	pod 'Alamofire'
	pod 'SwiftyJSON'
  target 'MFB_IOS_PROJECTTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Alamofire'
	pod 'SwiftyJSON'
  end

end
